export const flags: Record<string, string> = {
  China: "cn",
  Russia: "ru",
  Kazakhstan: "kz",
  France: "fr",
  Uzbekistan: "uz",
  Pakistan: "pk",
  India: "in",
  Nigeria: "ng",
  Mexico: "mx",
  Ethiopia: "et",
  Canada: "ca",
  USA: "us",
  Egypt: "eg",
  Myanmar: "mm",
  Zimbabwe: "zw",
  Rwanda: "rw",
  Cuba: "cu",
  Philippines: "ph",
  Brazil: "br",
  Ukraine: "ua",
  Iraq: "iq",
  Poland: "pl",
  Morocco: "ma",
  "Saudi Arabia": "sa",
};
