export const projectsInfo = [
        {
            title: "Durak Online",
            date: "Jun 2020 - Aug 2020",
            desc_1: "The multiplayer online card game. (2 or 3 players)",
            desc_2: "More than 500,000 game lobbies were created.",
            desc_3: "Built high performant game server based on gRPC.",
            icon_1: "/icons/csharp.svg",
            icon_2: "/icons/unity.svg",
            icon_3: "/icons/grpc.svg",
            icon3width: 55,
            icon3height: 26,
            appLogo: "/icons/bsgames.png",
        },
        {
            title: "Beevision.tech",
            date: "Oct 2020",
            desc_1: "Web service that identifies COVID-19 by X-ray lung image.",
            desc_2: "Deployed Machine Learning model.",
            desc_3: "Designed and made up advertisement and diagnostic website.",
            icon_1: "/icons/typescript.png",
            icon_2: "/icons/react.svg",
            icon_3: "/icons/django.svg",
            icon3width: 55,
            icon3height: 26,
            appLogo: "/icons/beevision.png",
        },
        {
            title: "Neupusti.net",
            date: "May 2018 - Jul 2019",
            desc_1: "Educational website with over 30,000 users.",
            desc_2: "Made up complex ReactJSX components from Figma.",
            desc_3: "Retrieved and parsed data from the server.",
            icon_1: "/icons/typescript.png",
            icon_2: "/icons/react.svg",
            icon_3: "/icons/redux.svg",
            icon3width: 36,
            icon3height: 36,
            appLogo: "/icons/neupusti.png",
        },
    ];
